import { MarkerType, type Edge, type Node } from 'reactflow'
import { normalizeArchimateElementData } from '@/modules/project-management/lib/integrationArchimateNotationCatalog'
import type { ArchimateElementNodeData, ArchimateNodeData } from './integrationArchitectureTypes'

export function buildDefaultIntegrationArchitecture(): {
  nodes: Node<ArchimateNodeData>[]
  edges: Edge[]
} {
  const nodes: Node<ArchimateNodeData>[] = [
    {
      id: 'boundary-business-app',
      type: 'archimateBoundary',
      position: { x: 40, y: 120 },
      data: { kind: 'boundary', title: 'Business / Application Collaboration Boundary' },
      style: { width: 770, height: 430 },
      zIndex: 0,
    },
    {
      id: 'boundary-tech',
      type: 'archimateBoundary',
      position: { x: 860, y: 120 },
      data: { kind: 'boundary', title: 'Technology / External System Boundary' },
      style: { width: 440, height: 430 },
      zIndex: 0,
    },
    {
      id: 'canvas-notes',
      type: 'archimateNote',
      position: { x: 840, y: 20 },
      data: {
        kind: 'note',
        title: 'Canvas Notes',
        lines: [
          'Modeled with ArchiMate-inspired layers: business role, application components and services, application data objects, and technology nodes.',
          'Primary routes: synchronous serving, asynchronous flow, and controlled data access into internal and external delivery targets.',
        ],
      },
      style: { width: 470, height: 78 },
      zIndex: 2,
    },
    {
      id: 'legend',
      type: 'archimateLegend',
      position: { x: 40, y: 580 },
      data: { kind: 'legend' },
      style: { width: 1270, height: 82 },
      zIndex: 2,
    },
    {
      id: 'portfolio-governance',
      type: 'archimateElement',
      position: { x: 70, y: 195 },
      data: {
        kind: 'element',
        layer: 'business',
        stereotype: 'Business Role',
        title: 'Komite Multi Finance',
        description: ['Sponsor ide, review,', 'dan pemilik prioritas'],
        variant: 'business-role',
      },
      style: { width: 180 },
    },
    {
      id: 'idea-engine',
      type: 'archimateElement',
      position: { x: 310, y: 160 },
      data: {
        kind: 'element',
        layer: 'application',
        stereotype: 'Application Component',
        title: 'Idea Intelligence Engine',
        description: ['Pengayaan AI, scoring risiko,', 'dan orkestrasi rekomendasi'],
        variant: 'application-component',
      },
      style: { width: 210 },
    },
    {
      id: 'api-gateway',
      type: 'archimateElement',
      position: { x: 570, y: 160 },
      data: {
        kind: 'element',
        layer: 'application',
        stereotype: 'Application Component',
        title: 'API Gateway',
        description: ['Enforcement kebijakan, authz,', 'routing, dan observability'],
        variant: 'application-component',
      },
      style: { width: 210 },
    },
    {
      id: 'recommendation-api',
      type: 'archimateElement',
      position: { x: 310, y: 300 },
      data: {
        kind: 'element',
        layer: 'application',
        stereotype: 'Application Service',
        title: 'API Rekomendasi AI',
        description: ['Permukaan eksekusi sinkron'],
        variant: 'application-service',
      },
      style: { width: 210 },
    },
    {
      id: 'integration-hub',
      type: 'archimateElement',
      position: { x: 570, y: 300 },
      data: {
        kind: 'element',
        layer: 'application',
        stereotype: 'Application Service',
        title: 'Hub Integrasi',
        description: ['Orkestrasi API, event, dan batch'],
        variant: 'application-service',
      },
      style: { width: 210 },
    },
    {
      id: 'forecast-signal-package',
      type: 'archimateElement',
      position: { x: 310, y: 450 },
      data: {
        kind: 'element',
        layer: 'data',
        stereotype: 'Data Object',
        title: 'Paket Sinyal SLA KPR',
        description: ['Indikator historis dan real-time', 'keterlambatan persetujuan'],
        variant: 'data-object',
      },
      style: { width: 210 },
    },
    {
      id: 'insight-outcome',
      type: 'archimateElement',
      position: { x: 570, y: 450 },
      data: {
        kind: 'element',
        layer: 'data',
        stereotype: 'Data Object',
        title: 'Hasil Insight',
        description: ['Paket keputusan untuk', 'consumer downstream'],
        variant: 'data-object',
      },
      style: { width: 210 },
    },
    {
      id: 'crm-platform',
      type: 'archimateElement',
      position: { x: 900, y: 170 },
      data: {
        kind: 'element',
        layer: 'technology',
        stereotype: 'Technology Node',
        title: 'Platform CRM',
        description: ['Pertukaran data nasabah', 'dan status persetujuan'],
        variant: 'technology-node',
      },
      style: { width: 150 },
    },
    {
      id: 'erp-platform',
      type: 'archimateElement',
      position: { x: 1108, y: 170 },
      data: {
        kind: 'element',
        layer: 'technology',
        stereotype: 'Technology Node',
        title: 'Platform LOS/ERP',
        description: ['Publikasi event approval', 'dan konfirmasi finansial'],
        variant: 'technology-node',
      },
      style: { width: 150 },
    },
    {
      id: 'data-platform',
      type: 'archimateElement',
      position: { x: 900, y: 300 },
      data: {
        kind: 'element',
        layer: 'technology',
        stereotype: 'Technology Node',
        title: 'Data Platform',
        description: ['Konsolidasi histori SLA dan', 'dataset feature engineering'],
        variant: 'technology-node',
      },
      style: { width: 150 },
    },
    {
      id: 'external-services',
      type: 'archimateElement',
      position: { x: 1108, y: 300 },
      data: {
        kind: 'element',
        layer: 'technology',
        stereotype: 'Technology Node',
        title: 'Layanan Eksternal',
        description: ['Verifikasi dokumen eksternal', 'dan data pendukung risiko'],
        variant: 'technology-node',
      },
      style: { width: 150 },
    },
    {
      id: 'virea-delivery',
      type: 'archimateElement',
      position: { x: 1004, y: 430 },
      data: {
        kind: 'element',
        layer: 'technology',
        stereotype: 'Technology Node',
        title: 'Workspace Delivery',
        description: ['Workspace eksekusi dan', 'target aksi downstream'],
        variant: 'technology-node',
      },
      style: { width: 150 },
    },
  ]

  const edges: Edge[] = [
    {
      id: 'serving-governance-idea-engine',
      source: 'portfolio-governance',
      target: 'idea-engine',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Serving',
      labelStyle: { fill: '#334155', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
    {
      id: 'serving-idea-engine-api-gateway',
      source: 'idea-engine',
      target: 'api-gateway',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Serving',
      labelStyle: { fill: '#334155', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
    {
      id: 'serving-idea-engine-recommendation-api',
      source: 'idea-engine',
      target: 'recommendation-api',
      sourceHandle: 'source-bottom',
      targetHandle: 'target-top',
      type: 'smoothstep',
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
    {
      id: 'serving-api-gateway-integration-hub',
      source: 'api-gateway',
      target: 'integration-hub',
      sourceHandle: 'source-bottom',
      targetHandle: 'target-top',
      type: 'smoothstep',
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
    {
      id: 'flow-recommendation-api-integration-hub',
      source: 'recommendation-api',
      target: 'integration-hub',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Flow',
      labelStyle: { fill: '#475569', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#334155' },
      style: { stroke: '#334155', strokeWidth: 2, strokeDasharray: '6 6' },
    },
    {
      id: 'access-recommendation-api-forecast-signal',
      source: 'recommendation-api',
      target: 'forecast-signal-package',
      sourceHandle: 'source-bottom',
      targetHandle: 'target-top',
      type: 'smoothstep',
      label: 'Access',
      labelStyle: { fill: '#475569', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#475569' },
      style: { stroke: '#475569', strokeWidth: 2, strokeDasharray: '3 5' },
    },
    {
      id: 'access-integration-hub-insight-outcome',
      source: 'integration-hub',
      target: 'insight-outcome',
      sourceHandle: 'source-bottom',
      targetHandle: 'target-top',
      type: 'smoothstep',
      markerEnd: { type: MarkerType.ArrowClosed, color: '#475569' },
      style: { stroke: '#475569', strokeWidth: 2, strokeDasharray: '3 5' },
    },
    {
      id: 'serving-integration-hub-crm',
      source: 'integration-hub',
      target: 'crm-platform',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Serving',
      labelStyle: { fill: '#334155', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
    {
      id: 'flow-integration-hub-erp',
      source: 'integration-hub',
      target: 'erp-platform',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Flow',
      labelStyle: { fill: '#475569', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#334155' },
      style: { stroke: '#334155', strokeWidth: 2, strokeDasharray: '6 6' },
    },
    {
      id: 'access-integration-hub-data-platform',
      source: 'integration-hub',
      target: 'data-platform',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Access',
      labelStyle: { fill: '#475569', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#475569' },
      style: { stroke: '#475569', strokeWidth: 2, strokeDasharray: '3 5' },
    },
    {
      id: 'flow-integration-hub-external-services',
      source: 'integration-hub',
      target: 'external-services',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Flow',
      labelStyle: { fill: '#475569', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#334155' },
      style: { stroke: '#334155', strokeWidth: 2, strokeDasharray: '6 6' },
    },
    {
      id: 'serving-insight-outcome-virea',
      source: 'insight-outcome',
      target: 'virea-delivery',
      sourceHandle: 'source-right',
      targetHandle: 'target-left',
      type: 'smoothstep',
      label: 'Serving',
      labelStyle: { fill: '#334155', fontSize: 10, fontWeight: 500 },
      labelBgStyle: { fill: '#ffffff', fillOpacity: 0.9 },
      labelBgPadding: [4, 2],
      markerEnd: { type: MarkerType.ArrowClosed, color: '#0f172a' },
      style: { stroke: '#0f172a', strokeWidth: 2 },
    },
  ]

  return { nodes, edges }
}

export function normalizeIntegrationNodesForCanvas(nodes: Node<ArchimateNodeData>[]): Node<ArchimateNodeData>[] {
  return nodes.map((node) => {
    if (node.type === 'archimateLegend') {
      return { ...node, draggable: false, selectable: false, connectable: false }
    }
    if (node.type === 'archimateElement') {
      return {
        ...node,
        draggable: true,
        selectable: true,
        connectable: true,
        data: normalizeArchimateElementData(node.data as ArchimateElementNodeData),
      }
    }
    return { ...node, draggable: true, selectable: true, connectable: false }
  })
}

export function cloneDefaultIntegrationArchitecture() {
  const { nodes, edges } = buildDefaultIntegrationArchitecture()
  return {
    nodes: normalizeIntegrationNodesForCanvas(JSON.parse(JSON.stringify(nodes)) as Node<ArchimateNodeData>[]),
    edges: JSON.parse(JSON.stringify(edges)) as Edge[],
  }
}
